---
- name: Configure postgres repos, epel, yum-utils
  yum:
    name:
      - https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
      - epel-release
      - yum-utils
      - python-psycopg2
    state: present